<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Custom fonts for this template-->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <?php $this->assets_css('app.css'); ?>
    <?php $this->assets_css('fontawesome/css/all.css'); ?>
    <?php $this->theme('white'); ?>
    
    <title>Default</title>
</head>
<body>
    <section id="content-area">
        <div class="container">
            <?php $this->renderContent() ?>
        </div>
    </section>
</body>
</html>